#!/usr/bin/env php
<?php

use Tempest\Console\ConsoleApplication;
use Tempest\Discovery\DiscoveryLocation;

require_once getcwd() . '/vendor/autoload.php';

ConsoleApplication::boot(
        discoveryLocations: [
                new DiscoveryLocation('Tempest\Testing\Tests\Fixtures', __DIR__ . '/tests/Fixtures')
        ],
)->run();

exit;